development:
  adapter: sqlite3
  database: development.sqlite3

test:
  adapter: sqlite3
  database: development.sqlite3

production:
  adapter: postgresql
  database: productiom #rename this to whatever you want
  username: username
  password: password
  host: localhost
